spring:
  profiles:
    active:
    - local
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:~/lightbiny-search
      driver-class-name: org.h2.Driver
      username: sa
      password:

logging:
  level:
    lightbiny: DEBUG   
    org.springframework.web.reactive: DEBUG

my:
  search-provider:
    default: kakao,naver 
    kakao:
      http-url: "https://dapi.kakao.com/v2/local/search/keyword.json"
      api-key: 
    naver:
      http-url: "https://openapi.naver.com/v1/search/local.json"
      client-id: 
      client-secret: 
